### ISSUE TITLE
Should `esbuild.install --if-missing` check also if outdated

### ISSUE THREAD

**Issue by cw789** [phoenixframework/esbuild#16]
Or should I add a `--update-only` flag?

What do you thing?

**Comment by josevalim** [comment]
Checking the version is a good idea. Can you please send a PR?

**Comment by josevalim** [comment]
I had some free time and I will push it. :)

**Comment by cw789** [comment]
Ohh, my PR is up. By checking `Esbuild.configured_version()` we will unexpectedly update for users if the latest_known version within esbuild is updated and no version is configured.

**Comment by josevalim** [comment]
@cw789 I think that behaviour is the desired one, after all, esbuild is under a lock file too. Otherwise people on the same esbuild version will get different outputs depending if they ran `mix esbuild.install` in a previous version, no?

**Comment by cw789** [comment]
You're right. Got my head around. Thanks for learning.

**Comment by josevalim** [comment]
Thank you for double checking and once again, sorry for the double effort. :)
