### ISSUE TITLE
Allow run without config

### ISSUE THREAD

**Issue by dnsbty** [phoenixframework/esbuild#18]
Thanks for the awesome work on this library!

I wanted to propose that a flag be added to allow `mix esbuild` to run without loading the application configuration.

In particular, I'm trying to build my static assets inside of a container in a continuous deployment pipeline. My `config/runtime.exs` file throws an exception if any of a number of environment variables aren't set, and typically none of those variables are set during the build process.

I'm currently working around this by calling `mix esbuild` before copying the runtime configuration file into the container, but it would be nice if I could specify all configuration via arguments to the mix task and specify that the configuration shouldn't be used just when running in my build pipeline.

**Comment by josevalim** [comment]
Sounds good to me. We can support a --no-runtime-config option. You can use OptionParser.parse_head so we parse only the beginning of the argv and we stop as soon as we see a non-flag. So you can do this:

    mix esbuild --no-runtime-config default ...

Note how it has to come before the environment. Effectively we have:

    mix esbuild TASK_OPTIONS PROFILE ESBUILD_ARGS

Can you please send a PR? :)

**Comment by cw789** [comment]
I've had the same circumstances (CI build process).
But now I just set an `CI` environment variable and check for it additionally to `config_env/1` === `:prod` via `System.get_env/1` in runtime.exs.
