### ISSUE TITLE
Does not work with 32bit arm

### ISSUE THREAD

**Issue by hez** [phoenixframework/esbuild#21]
It looks like there is support for 64bit arm (arch aarch64) but not 32bit arm (arm, arm7, etc) I think it would be as simple as adding a clause for "arm".

I tried this out and it appears to work: https://github.com/phoenixframework/esbuild/compare/main...hez:feature/linux-arm?expand=1#diff-817be7445555ff97e4b7a5c8139e8e7e953cd62b9175b157793e979ad85dd79dR193

**Comment by josevalim** [comment]
Please do send a PR!
