### ISSUE TITLE
Run will fail again on MIX_ENV=prod in default Phoenix config

### ISSUE THREAD

**Issue by cw789** [phoenixframework/esbuild#23]
With https://github.com/phoenixframework/phoenix/pull/4468 (No secret key base fallback) we will again have the trouble
that running esbuild will fail if used with MIX_ENV=prod and default Phoenix config.

```
** (RuntimeError) environment variable SECRET_KEY_BASE is missing.
```

Any ideas how we can get around this?

**Comment by josevalim** [comment]
Yes, you are correct. A pull request is welcome!

**Comment by cw789** [comment]
Ok. I'll do.
