### ISSUE TITLE
Package esbuild binaries in project

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/esbuild#38]
This will avoid depending on the npm registry to fetch the binaries on demand

**Comment by kinson** [comment]
Hi @chrismccord 👋🏻 

I just came across this issue. If it's still something worth doing (and I see the value in not depending on NPM) then I would be interested in taking a stab at it!

From looking at the `Esbuild` module, and the list of [supported targets](https://github.com/evanw/esbuild/tree/master/npm) for esbuild we could include 16 of the 21 available targets (all targets excluding `windows-wasm`, `esbuild-linux-s390x`, `esbuild-linux-riscv64`, `esbuild-linux-ppc64le`, `esbuild-linux-mips64le`) in the project. Let me know if this assumption is wrong and there are other targets this project cannot support.

My assumption is that we'd want to include the compressed files to save some space. However even compressed each binary seems to be about 3 MB in size (based on a few samples). Thus, including 16 binaries at 3 MB per binary would add 48 MB to the project. Is increasing the size of the project a concern? I suppose we could delete the unused binaries after the OS is identified and the appropriate binary is decompressed.

Let me know if I am misunderstanding what you are thinking for this solution, and thank you in advance for your help 🙂

**Comment by josevalim** [comment]
Closing this for now.
