### ISSUE TITLE
docker alpine linux armv7 - esbuild is not available for architecture: armv7-alpine-linux-musleabihf

### ISSUE THREAD

**Issue by joerggollnick** [phoenixframework/esbuild#40]
Building my phoenix app as docker container fails on 32bit armv7 alpine linux (Raspberry Pi Host).

erlang identifies architecture as armv7 
```
iex(1)> :erlang.system_info(:system_architecture)
'armv7-alpine-linux-musleabihf'
```

Debian identifies same platform as `'arm-unknown-linux-gnueabihf'`

From my point of view, an extra line before https://github.com/phoenixframework/esbuild/blob/e90b75f4627bf39880667bc02a924d620ce00f4c/lib/esbuild.ex#L252 is needed:

`"armv7" -> "#{osname}-arm"`

**Comment by josevalim** [comment]
Yes, please do send a PR!
