### ISSUE TITLE
Heads up: upcoming change to esbuild package names

### ISSUE THREAD

**Issue by evanw** [phoenixframework/esbuild#52]
This is a heads up that I'm planning on changing esbuild's package names in an upcoming release. The packages are being moved under the `@esbuild/` scope to avoid name collisions. I'm also changing the `os` and `cpu` strings to be exactly equal to the ones returned by node (previously a few of them weren't consistent). You can find the work-in-progress change that does this here: https://github.com/evanw/esbuild/pull/2508.

More context:  I've had a problem with people trying to add support for a new platform to esbuild and then registering the package name themselves, which doesn't work because then I don't control the package name. Using a scope prevents this problem.

**Comment by josevalim** [comment]
Thanks for the heads up, it looks straight-forward to catch up!

**Comment by evanw** [comment]
Another heads up that this change has now been released: https://github.com/evanw/esbuild/releases/tag/v0.16.0. The new package names are in the release notes.

**Comment by chrismccord** [comment]
❤️❤️❤️🐥🔥
