### ISSUE TITLE
install fails with empty http_proxy env-var

### ISSUE THREAD

**Issue by milahu** [phoenixframework/esbuild#56]
https://github.com/phoenixframework/esbuild/blob/ad8255f03bd01fa4e1133d1076a838a709a22079/lib/esbuild.ex#L310

see https://github.com/dwyl/phoenix-liveview-counter-tutorial/issues/114

**Comment by josevalim** [comment]
Last time we checked this was common behaviour across other tools, so we don't plan to change it. Since we log when the proxy is used, I recommend unsetting them if they are empty. Thank you!
