### ISSUE TITLE
Issues running under Windows

### ISSUE THREAD

**Issue by pablodavila95** [phoenixframework/esbuild#6]
The esbuild executable isn't called "esbuild" but rather "esbuild.exe", which was causing exceptions when attempting to run it. I modified install/0 :

```
case :os.type() do
      {:win32, _} ->
        File.cp!(Path.join([tmp_dir, "package", "esbuild.exe"]), bin_path)
      _ ->
        File.cp!(Path.join([tmp_dir, "package", "bin", "esbuild"]), bin_path)
end
```

This way the correct binary is placed in the _build folder. It seems that modifying bin_path/0 and the mix.exs aliases isn't necessary (to add the .exe suffix) as everything seems to be running fine and changes in the stylesheets are being correctly rebuilt.

**Comment by wojtekmach** [comment]
If you convert it to a PR, Ill gladly merge it!
