### ISSUE TITLE
Cannot download esbuild after latest npm path changes

### ISSUE THREAD

**Issue by jamesvl** [phoenixframework/esbuild#71]
It looks like [this PR](https://github.com/phoenixframework/esbuild/pull/64/files) changed the path from which `esbuild` is fetched from the npm registry, which has broken my ability to install it via `mix esbuild.install`.

The path it attempts to reach is `https://registry.npmjs.org/@esbuild/linux-x64/0.19.8`

But the path it should be fetching from is e.g. `https://registry.npmjs.org/@esbuild/linux-x64/-/linux-x64-0.19.8.tgz`

(You can see this path in the [registry.npmjs.org JSON](https://registry.npmjs.org/@esbuild/linux-x64/) under versions > [num] > dist > tarball.)

Is this is in anticipation of build file changes that haven't been released yet?

**Comment by guillego** [comment]
I'm having the same problem for the past 20 hours but not when I run `mix esbuild.install`, only when I'm running `mix assets.deploy` in my Dockerfile (using a fly.io remote builder and locally).

Not sure if it's related, but it happens both in 0.7.1 and 0.8.1

```
=> [builder 13/17] RUN mix assets.deploy                                          220.7s
 => => # Rebuilding...
 => => # Done in 743ms.
 => => # 12:15:08.834 [debug] Downloading esbuild from https://registry.npmjs.org/@esbuil
 => => # d/linux-x64/-/linux-x64-0.17.11.tgz
```

**Comment by josevalim** [comment]
@jamesvl that's correct. We reach "https://registry.npmjs.org/@esbuild/linux-x64/0.19.8" to get the metadata, and then we get the tarball pointed by the metadata. In my machine, it does end-up downloading: "https://registry.npmjs.org/@esbuild/darwin-arm64/-/darwin-arm64-0.17.11.tgz" and in your case it will download "https://registry.npmjs.org/@esbuild/linux-x64/-/linux-x64-0.19.4.tgz". So everything looks correct to me and also works here. Are you running into any problem in particular? Can you please provide more info?

**Comment by jamesvl** [comment]
On Friday our CI build was emitting this:

```
#25 1.629 18:57:50.213 [debug] Downloading esbuild from https://registry.npmjs.org/@esbuild/linux-x64/0.19.3
#25 61.97 
#25 61.97 18:58:50.547 [error] Task #PID<0.201.0> started from Esbuild.Supervisor terminating
#25 61.97 ** (RuntimeError) couldn't fetch https://registry.npmjs.org/@esbuild/linux-x64/0.19.3: {:ok, {{~c"HTTP/1.1", 503, ~c"Service Unavailable"}, [{~c"connection", ~c"keep-alive"}, {~c"date", ~c"Fri, 08 Dec 2023 18:58:50 GMT"}, {~c"server", ~c"cloudflare"}, {~c"content-length", ~c"31"}, {~c"content-type", ~c"application/json"}, {~c"cf-ray", ~c"83273c827e2302bc-ORD"}], "{\"error\":\"Service Unavailable\"}"}}
#25 61.97 
#25 61.97 You may also install the "esbuild" executable manually, see the docs: https://hexdocs.pm/esbuild
#25 61.97 
#25 61.97     (esbuild 0.8.1) lib/esbuild/npm_registry.ex:65: Esbuild.NpmRegistry.fetch_file!/1
#25 61.97     (esbuild 0.8.1) lib/esbuild/npm_registry.ex:39: Esbuild.NpmRegistry.fetch_package!/2
#25 61.97     (esbuild 0.8.1) lib/esbuild.ex:238: Esbuild.install/0
#25 61.97     (elixir 1.15.7) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2
#25 61.97 Function: #Function<0.45081244/0 in Esbuild.install>
```

Running `esbuild.install` locally gave me the same 503, but looking at the registry file and downloading it manually worked fine. (Note the attempted URL lacks the full `/linux-x64/-/linux-x64-0.19.8.tgz` that the registry file includes.)

I just tried it again, and the short URL is working successfully though. My conclusion would be that a redirect in the registry was temporarily failing on Friday and is now fixed.

Seems fine to close this out!

**Comment by josevalim** [comment]
Yeah, it seems like a failure on npm. Thanks!
