### ISSUE TITLE
Stylesheets and copying assets?

### ISSUE THREAD

**Issue by joshchernoff** [phoenixframework/esbuild#8]
The JS pipeline is only one part of the whole asset management.  How will this pattern fit in with the other parts of static asset management? 

For example, this is currently how I've been integrating Esbuild + Postcss

```
watchers: [
    "#{esbuild}": [
      "./js/app.js",
      "--target=es2020",
      "--bundle",
      "--outdir=../priv/static/js",
      "--color=true",
      "--log-level=debug",
      "--sourcemap",
      "--watch",
      cd: Path.expand("../assets", __DIR__)
    ],
    "#{postcss}": [
      "./css/app.css",
      "--dir",
      "../priv/static/css",
      "--verbose",
      "-w",
      "-m",
      cd: Path.expand("../assets", __DIR__),
      env: [{"NODE_ENV", "development"}, {"TAILWIND_MODE", "watch"}]
    ],
    "#{cpx}": [
      "./static/**/*",
      "../priv/static",
      "-v",
      "--watch",
      cd: Path.expand("../assets", __DIR__)
    ]
  ]
  ```
  
  The only real issue I've run into are zombie processes left by cpx. This has been called out before and I believe there is even a PR to fix it.  
  
  Back to my question, how should postcss and other asset management needs integrate following this pattern?

**Comment by josevalim** [comment]
Pretty much in the way that you did. :) The [example app](https://github.com/josevalim/phx_esbuild_demo/) has some answers too:

1. For images and static assets, we flipped things around: all statics now go directly into priv/static and the compiled assets go to priv/static/assets, which is now the only folder gitignored. This way you no longer need something like cpx.

2. For css, then you can bring another pipeline, as you showed and [as seen in this PR](https://github.com/josevalim/phx_esbuild_demo/pull/3)
